version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  backend:
    image: java-ecommerce-rest
    container_name: ecommerce-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always

    depends_on:
      - db
