version: "3.8"

services:
  mysqldb:
    container_name: "mysqldb"
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=root1

    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_schema/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  ecommerce:
    container_name: "ecommerce"
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./ecommerceImages/:/var/lib/ecommerceImages
    build:
      context: "./"
      dockerfile: "Dockerfile"
    expose:
      - "8080"
    depends_on:
      - mysqldb